### Site Settings ###
title               : KL05
description         : >-
                      "Mathematic, Julia Language and Machine Learning."
baseurl             : "/kl05"
repository          : YoussefRaafatNasry/portfolYOU     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji
  - jekyll-target-blank



### Navbar Settings ###
# nav_exclude:                                            # The following paths are excluded from navbar
#  - pages/tags.html
#  - pages/404.html
#  - pages/index.md


### Author Info ###
author:
  name              : Carlos Eduardo
  email             : username@domain.com
  github            : KL05
  instagram         : kl05e
#  linkedin          : your_username
#  medium            : your_username
# stackoverflow     : your_user_id


### Posts ###
permalink: /blog/:title


### Collections ###
#collections:
#  projects:
#    output: true
#    permalink: /projects/:name


### Defaults for collections ###
#defaults:
#  - scope:
#      path: ""
#      type: "projects"
#    values:
#      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
